### PR TITLE
Segments asymmetry fix

### PR DESCRIPTION
**Pull request by marknutter**
Should be symmetric now!

### CODE REVIEW

**Comment by ps2** [comment]
We don't have anything posting to interaction_periods. Could you remove that endpoint?

**Comment by ps2** [comment]
Could you extract the special values (300, 0.7, 10) as constants/vars, so they have names that give a hint as to what they represent?

**Comment by ps2** [comment]
It appears to be symmetric. 👍  I see one more thing that should be tackled here: it seems like some entities are being listed in the display despite having no interaction periods.  They should be removed.

**Comment by marknutter** [comment]
The changes should actually go into the `analysis` branch since that's includes the final implementation where the segments are generated by a worker rather than on the fly. I will make these changes over there.

**Comment by ps2** [comment]
Should I merge this, or are you making all these changes in the analysis branch? Not sure I follow 100%.

**Pull request closed without merging**
